In [5]:
# Importing the libraries
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation 
%matplotlib inline 
sns.set(color_codes=True)

import sklearn.preprocessing as preproc

from sklearn.neighbors import KNeighborsClassifier

from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

import os

# hide warnings
import warnings
warnings.filterwarnings('ignore')
sns.set_theme();

In [4]:
tweets = pd.read_csv("file:///home/chakuunaa/BD_ADA_CA2sem2/data/stocktweet.csv")

tweets.head()

,id,date,ticker,tweet
0,100001,01/01/2020,AMZN,$AMZN Dow futures up by 100 points already 🥳
1,100002,01/01/2020,TSLA,$TSLA Daddy's drinkin' eArly tonight! Here's t...
2,100003,01/01/2020,AAPL,$AAPL We’ll been riding since last December fr...
3,100004,01/01/2020,TSLA,"$TSLA happy new year, 2020, everyone🍷🎉🙏"
4,100005,01/01/2020,TSLA,"$TSLA haha just a collection of greats...""Mars..."

In [5]:
tweets.shape

(10000, 4)

In [6]:
aapl = pd.read_csv("file:///home/chakuunaa/BD_ADA_CA2sem2/data/stockprice/AAPL.csv")

aapl.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-12-31,72.482498,73.419998,72.379997,73.412498,71.520821,100805600
1,2020-01-02,74.059998,75.150002,73.797501,75.087502,73.152649,135480400
2,2020-01-03,74.287498,75.144997,74.125000,74.357498,72.441460,146322800
3,2020-01-06,73.447502,74.989998,73.187500,74.949997,73.018677,118387200
4,2020-01-07,74.959999,75.224998,74.370003,74.597504,72.675278,108872000