In [1]:
import pandas as pd
import os

from pymongo import MongoClient
from sqlalchemy import create_engine

In [2]:
tweets = pd.read_csv("../data/stocktweet.csv")

tweets.head()

,id,date,ticker,tweet
0,100001,01/01/2020,AMZN,$AMZN Dow futures up by 100 points already 🥳
1,100002,01/01/2020,TSLA,$TSLA Daddy's drinkin' eArly tonight! Here's t...
2,100003,01/01/2020,AAPL,$AAPL We’ll been riding since last December fr...
3,100004,01/01/2020,TSLA,"$TSLA happy new year, 2020, everyone🍷🎉🙏"
4,100005,01/01/2020,TSLA,"$TSLA haha just a collection of greats...""Mars..."

In [3]:
client = MongoClient("mongodb://localhost:27017/")
db = client["stock_project"]

collection = db["tweets"]

In [4]:
collection.delete_many({})

collection.insert_many(tweets.to_dict("records"))

collection.count_documents({})

10000

In [5]:
list(collection.find({}, {"_id": 0}).limit(5))

[{'id': 100001,
  'date': '01/01/2020',
  'ticker': 'AMZN',
  'tweet': '$AMZN Dow futures up by 100 points already 🥳'},
 {'id': 100002,
  'date': '01/01/2020',
  'ticker': 'TSLA',
  'tweet': "$TSLA Daddy's drinkin' eArly tonight! Here's to a PT of ohhhhh $1000 in 2020! 🍻"},
 {'id': 100003,
  'date': '01/01/2020',
  'ticker': 'AAPL',
  'tweet': '$AAPL We’ll been riding since last December from $172.12 what to do. Decisions decisions hmm 🤔. I have 20 mins to decide. Any suggestions?'},
 {'id': 100004,
  'date': '01/01/2020',
  'ticker': 'TSLA',
  'tweet': '$TSLA happy new year, 2020, everyone🍷🎉🙏'},
 {'id': 100005,
  'date': '01/01/2020',
  'ticker': 'TSLA',
  'tweet': '$TSLA haha just a collection of greats..."Mars" rofl 😈😎🌠⏫🔮💸👏💪🚀🎆🎇📣🎉🎊 *bork*'}]

In [6]:
engine = create_engine(
    "mysql+mysqlconnector://stockuser:stockpass@localhost/stock_project"
)

In [7]:
stock_folder = "../data/stockprice"

for file in os.listdir(stock_folder):

    if file.endswith(".csv"):

        ticker = (
            file.replace(".csv", "")
            .replace("-", "_")
            .replace("^", "")
        )

        df = pd.read_csv(os.path.join(stock_folder, file))

        df["Ticker"] = ticker

        table_name = f"price_{ticker.lower()}"

        df.to_sql(
            table_name,
            con=engine,
            if_exists="replace",
            index=False
        )

print("All stock files inserted into MySQL")

All stock files inserted into MySQL

In [8]:
pd.read_sql("SHOW TABLES;", con=engine)

   Tables_in_stock_project
0               price_aapl
1               price_abnb
2                price_amt
3               price_amzn
4                 price_ba
5               price_baba
6                price_bac
7               price_bkng
8              price_brk_a
9              price_brk_b
10               price_ccl
11               price_cvx
12               price_dis
13                price_fb
14              price_goog
15             price_googl
16              price_gspc
17                price_hd
18               price_jnj
19               price_jpm
20                price_ko
21               price_low
22                price_ma
23               price_mcd
24              price_meta
25              price_msft
26              price_nflx
27               price_nke
28              price_nvda
29               price_pfe
30                price_pg
31              price_pypl
32              price_sbux
33                price_tm
34              price_tsla
35               price_tsm
36               price_unh
37               price_ups
38                 price_v
39               price_wmt
40               price_xom

In [9]:
pd.read_sql("SELECT * FROM price_aapl LIMIT 5;", con=engine)

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,2019-12-31,72.482498,73.419998,72.379997,73.412498,71.520821,100805600,AAPL
1,2020-01-02,74.059998,75.150002,73.797501,75.087502,73.152649,135480400,AAPL
2,2020-01-03,74.287498,75.144997,74.125000,74.357498,72.441460,146322800,AAPL
3,2020-01-06,73.447502,74.989998,73.187500,74.949997,73.018677,118387200,AAPL
4,2020-01-07,74.959999,75.224998,74.370003,74.597504,72.675278,108872000,AAPL