In [1]:
import pandas as pd

In [2]:
sentiment = pd.read_csv(
    "/home/chakuunaa/BD_ADA_CA2sem2/data/daily_sentiment.csv"
)

sentiment.head()

         date ticker  avg_sentiment  tweet_count
0  01/01/2020   AAPL       0.273200            1
1  01/01/2020   AMZN       0.000000            1
2  01/01/2020   TSLA       0.111975            4
3  01/02/2020   AAPL       0.261133            3
4  01/02/2020   AMZN       0.549900            1

In [3]:
aapl = pd.read_csv(
    "/home/chakuunaa/BD_ADA_CA2sem2/data/stockprice/AAPL.csv"
)

aapl.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-12-31,72.482498,73.419998,72.379997,73.412498,71.520821,100805600
1,2020-01-02,74.059998,75.150002,73.797501,75.087502,73.152649,135480400
2,2020-01-03,74.287498,75.144997,74.125000,74.357498,72.441460,146322800
3,2020-01-06,73.447502,74.989998,73.187500,74.949997,73.018677,118387200
4,2020-01-07,74.959999,75.224998,74.370003,74.597504,72.675278,108872000

In [5]:
aapl["Date"] = pd.to_datetime(aapl["Date"], dayfirst=True, errors="coerce")

sentiment["date"] = pd.to_datetime(sentiment["date"], dayfirst=True, errors="coerce")

In [6]:
aapl[["Date"]].head()

        Date
0 2019-12-31
1 2020-01-02
2 2020-01-03
3 2020-01-06
4 2020-01-07

In [7]:
sentiment[["date"]].head()

        date
0 2020-01-01
1 2020-01-01
2 2020-01-01
3 2020-02-01
4 2020-02-01

In [8]:
aapl_sentiment = sentiment[
    sentiment["ticker"] == "AAPL"
]

In [9]:
merged_aapl = pd.merge(
    aapl,
    aapl_sentiment,
    left_on="Date",
    right_on="date",
    how="left"
)

merged_aapl.head()

,Date,Open,High,Low,Close,Adj Close,Volume,date,ticker,avg_sentiment,tweet_count
0,2019-12-31,72.482498,73.419998,72.379997,73.412498,71.520821,100805600,NaT,NaN,NaN,NaN
1,2020-01-02,74.059998,75.150002,73.797501,75.087502,73.152649,135480400,2020-01-02,AAPL,0.376125,8.0
2,2020-01-03,74.287498,75.144997,74.125000,74.357498,72.441460,146322800,2020-01-03,AAPL,0.103833,6.0
3,2020-01-06,73.447502,74.989998,73.187500,74.949997,73.018677,118387200,2020-01-06,AAPL,0.779300,2.0
4,2020-01-07,74.959999,75.224998,74.370003,74.597504,72.675278,108872000,2020-01-07,AAPL,0.069367,3.0

In [10]:
merged_aapl["avg_sentiment"] = merged_aapl[
    "avg_sentiment"
].fillna(0)

In [11]:
features = merged_aapl[
    [
        "Date",
        "Close",
        "Volume",
        "avg_sentiment",
        "tweet_count"
    ]
]

features.head()

        Date      Close     Volume  avg_sentiment  tweet_count
0 2019-12-31  73.412498  100805600       0.000000          NaN
1 2020-01-02  75.087502  135480400       0.376125          8.0
2 2020-01-03  74.357498  146322800       0.103833          6.0
3 2020-01-06  74.949997  118387200       0.779300          2.0
4 2020-01-07  74.597504  108872000       0.069367          3.0

In [12]:
features.to_csv(
    "/home/chakuunaa/BD_ADA_CA2sem2/data/aapl_features.csv",
    index=False
)

In [13]:
companies = [
    "AAPL",
    "TSLA",
    "AMZN",
    "MSFT",
    "GOOG"
]